apiVersion: v1
kind: Service
metadata:
  name: details-svc
  namespace: cdps-21
  labels:
    app: details
spec:
  selector:
    app: details
  ports:
    - name: http
      port: 7070
      targetPort: 7070
  type: ClusterIP
