apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-deploy
  namespace: cdps-21
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
        - name: productpage
          image: europe-southwest1-docker.pkg.dev/cdps-pc2-485116/cdps-repo/cdps-productpage:g21
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TEAM_ID
              value: "21"
            - name: APP_OWNER
              value: "Aguilar-et-al"
            - name: DETAILS_HOSTNAME
              value: "details-svc"
            - name: REVIEWS_HOSTNAME
              value: "reviews"
            - name: RATINGS_HOSTNAME
              value: "ratings-svc"
