apiVersion: v1
kind: Service
metadata:
  name: ratings-svc
  namespace: cdps-21
  labels:
    app: ratings
spec:
  selector:
    app: ratings
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  type: ClusterIP
